# Generated by Django 5.2.6 on 2025-09-09 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigmaSoccersItemShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Item Name', max_length=120)),
                ('description', models.TextField(help_text='Item Description')),
                ('thumbnail', models.URLField(help_text='Image URL', max_length=330)),
                ('price', models.IntegerField(help_text='Price(rupiah)')),
                ('category', models.CharField(help_text='Item category (ex: Ball, Boots, Shirt, etc)', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='a Featured Item?')),
                ('rating', models.IntegerField(default=0, help_text='Drop a rating (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('brand', models.CharField(blank=True, help_text='Brand name(ex: Puma, Under Armour, Nike)', max_length=100, null=True)),
                ('stock', models.IntegerField(default=0, help_text='Available stock')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
