# Generated by Django 5.2.6 on 2025-09-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sigmasoccersitemshop_delete_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SigmaSoccersItemShop',
            new_name='FootballProducts',
        ),
    ]
