# Generated by Django 5.2.6 on 2025-09-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_sigmasoccersitemshop_footballproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballproducts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
