# Generated by Django 5.2.6 on 2025-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_footballproducts_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='item Name', max_length=255)),
                ('brand', models.CharField(help_text='item Name', max_length=255)),
                ('stock', models.IntegerField(help_text='Stock: ')),
            ],
        ),
    ]
